[manifest]
version = "0.1"
dump_lua = true
priority = 0

# [[patches]]
# [patches.pattern]
# target = "game.lua"
# pattern = '''{file = "resources/fonts/NotoSansSC-Bold.ttf", render_scale = self.TILESIZE*7, TEXT_HEIGHT_SCALE = 0.7, TEXT_OFFSET = {x=0,y=-35}, FONTSCALE = 0.12, squish = 0.9, DESCSCALE = 1.1},'''
# position = "at"
# payload = '''{file = "resources/fonts/NotoSansSC-Bold.ttf", render_scale = self.TILESIZE*7, TEXT_HEIGHT_SCALE = 0.9, TEXT_OFFSET = {x=0,y=-3}, FONTSCALE = 0.11, squish = 1, DESCSCALE = 1.1},'''
# match_indent = true

# 当前 Balasclo 版本
[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = "VERSION = VERSION..'-FULL'"
position = "after"
payload = "VERSION = VERSION..' (Balasclo v0.0.1)'"
overwrite = false
match_indent = true

# Steamodded 相关文本汉化
[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''label = {"MODS"},'''
position = "at"
payload = '''label = {"模组"},'''
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''label = "Mods",'''
position = "at"
payload = '''label = "模组",'''
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''label = " Steamodded Credits ",'''
position = "at"
payload = '''label = " Steamodded 鸣谢 ",'''
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''text = "List of Activated Mods",'''
position = "at"
payload = '''text = "已启用模组列表",'''
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''text = "List of Activated Mods",'''
position = "at"
payload = '''text = "已启用模组列表",'''
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''label = {" " .. modInfo.name .. " ", " By: " .. concatAuthors(modInfo.author) .. " "},'''
position = "at"
payload = '''label = {" " .. modInfo.name .. " ", "作者：" .. concatAuthors(modInfo.author) .. " "},'''
match_indent = true

# 减慢小丑牌名称渐入效果
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''pop_in_rate = 4,'''
position = "at"
payload = '''pop_in_rate = 1,'''
match_indent = true

# 使用轨道标签升级牌型的牌型名称本地化
[[patches]]
[patches.pattern]
target = "tag.lua"
pattern = '''handname= self.ability.orbital_hand,'''
position = "at"
payload = '''handname = localize(self.ability.orbital_hand, "poker_hands"),'''
match_indent = true

# “Not Allowed!”正确本地化
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''play_area_status_text("Not Allowed!")--localize('k_not_allowed_ex'), true)'''
position = "at"
payload = '''play_area_status_text(localize('k_not_allowed_ex'))'''
match_indent = true

# 页 x/x -> 第x/x页
[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''localize('k_page') .. ' ' .. tostring(i) .. '/' .. tostring(math.ceil(#G.P_CENTER_POOLS.Planet / 6)))'''
position = "at"
payload = ''''第' .. tostring(i) .. '/' .. tostring(math.ceil(#G.P_CENTER_POOLS.Planet / 6)) .. localize('k_page'))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''localize('k_page') .. ' ' .. tostring(i) .. '/' .. tostring(math.ceil(#G.P_CENTER_POOLS.Spectral / 9)))'''
position = "at"
payload = ''''第' .. tostring(i) .. '/' .. tostring(math.ceil(#G.P_CENTER_POOLS.Spectral / 9)) .. localize('k_page'))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''localize('k_page') .. ' ' .. tostring(i) .. '/' .. tostring(math.ceil(#G.P_CENTER_POOLS.Tarot / 11)))'''
position = "at"
payload = ''''第' .. tostring(i) .. '/' .. tostring(math.ceil(#G.P_CENTER_POOLS.Tarot / 11)) .. localize('k_page'))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''local currentPage = "Page " .. page .. "/" .. totalPages'''
position = "at"
payload = '''local currentPage = "第" .. page .. "/" .. totalPages .. "页"'''
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''table.insert(pageOptions, ("Page " .. i .. "/" .. totalPages))'''
position = "at"
payload = '''table.insert(pageOptions, ("第" .. i .. "/" .. totalPages .. "页"))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''table.insert(joker_options, localize('k_page')..' '..tostring(i)..'/'..tostring(math.ceil(#G.P_CENTER_POOLS.Joker/(5*#G.your_collection))))'''
position = "at"
payload = '''table.insert(joker_options, '第'..tostring(i)..'/'..tostring(math.ceil(#G.P_CENTER_POOLS.Joker/(5*#G.your_collection)))..localize('k_page'))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''table.insert(tarot_options, localize('k_page')..' '..tostring(i)..'/'..tostring(math.floor(#G.P_CENTER_POOLS.Tarot/11)))'''
position = "at"
payload = '''table.insert(tarot_options, '第'..tostring(i)..'/'..tostring(math.floor(#G.P_CENTER_POOLS.Tarot/11))..localize('k_page'))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''table.insert(booster_options, localize('k_page')..' '..tostring(i)..'/'..tostring(math.ceil(#G.P_CENTER_POOLS.Booster/8)))'''
position = "at"
payload = '''table.insert(booster_options, '第'..tostring(i)..'/'..tostring(math.ceil(#G.P_CENTER_POOLS.Booster/8))..localize('k_page'))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''table.insert(spectral_options, localize('k_page')..' '..tostring(i)..'/'..tostring(math.floor(#G.P_CENTER_POOLS.Spectral/9)))'''
position = "at"
payload = '''table.insert(spectral_options, '第'..tostring(i)..'/'..tostring(math.floor(#G.P_CENTER_POOLS.Spectral/9))..localize('k_page'))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''table.insert(voucher_options, localize('k_page')..' '..tostring(i)..'/'..tostring(math.ceil(#G.P_CENTER_POOLS.Voucher/(4*#G.your_collection))))'''
position = "at"
payload = '''table.insert(voucher_options, '第'..tostring(i)..'/'..tostring(math.ceil(#G.P_CENTER_POOLS.Voucher/(4*#G.your_collection)))..localize('k_page'))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''table.insert(challenge_options, localize('k_page')..' '..tostring(i)..'/'..tostring(math.ceil(#G.CHALLENGES/G.CHALLENGE_PAGE_SIZE)))'''
position = "at"
payload = '''table.insert(challenge_options, '第'..tostring(i)..'/'..tostring(math.ceil(#G.CHALLENGES/G.CHALLENGE_PAGE_SIZE))..localize('k_page'))'''
match_indent = true

# 随机商店副标题
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "function G.UIDEF.shop()"
position = "after"
payload = '''
function RollShopSub(seed)
    local vSub = localize('ph_improve_run')
    local shopSub = {
        vSub,
        "精打细算！",
        "消费无罪！",
        "Oh hi Johnny I didn't know it was you.",
        "客官里边请！",
        "命运之轮会欺骗你，但商店不会",
        "打造赛局最佳小丑阵容！",
        "更新日志：下架了金宝",
        "更新日志：上架了金宝",
        "留点资金吃利息？",
        "花 > 省",
        "接受信用卡！",
        "ALL IN!!!",
        "全场X折！",
        "金宝提醒您：早买早享受",
        "来点小丑牌？",
        "来点塔罗牌？",
        "来点星球牌？",
        "来点补充包？",
        "重掷即出好货！",
        "重掷即出负片！",
        "重掷即出镭射！",
        "重掷即出闪箔！",
        "重掷=浪费！",
        "你的贫穷让我沮丧！",
        "你的富裕让我痴狂！"
    }
    local sub = pseudorandom_element(shopSub, pseudoseed(seed))
    return sub
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.O, config={object = DynaText({string = {localize('ph_improve_run')}, colours = {lighten(G.C.GOLD, 0.3)},shadow = true, rotate = true, float = true, bump = true, scale = 0.5, spacing = 1, pop_in = 1.5, maxw = 4.3})}}'''
position = "at"
payload = '''{n=G.UIT.O, config={object = DynaText({string = {RollShopSub('ShopRandomSubGoBrr')}, colours = {lighten(G.C.GOLD, 0.3)},shadow = true, rotate = true, float = true, bump = true, scale = 0.5, spacing = 1, pop_in = 1.5, maxw = 4.3})}}'''
match_indent = true
