[manifest]
version = "0.1"
dump_lua = true
priority = 0

# [[patches]]
# [patches.pattern]
# target = "game.lua"
# pattern = '''{file = "resources/fonts/NotoSansSC-Bold.ttf", render_scale = self.TILESIZE*7, TEXT_HEIGHT_SCALE = 0.7, TEXT_OFFSET = {x=0,y=-35}, FONTSCALE = 0.12, squish = 0.9, DESCSCALE = 1.1},'''
# position = "at"
# payload = '''{file = "resources/fonts/NotoSansSC-Bold.ttf", render_scale = self.TILESIZE*7, TEXT_HEIGHT_SCALE = 0.9, TEXT_OFFSET = {x=0,y=-3}, FONTSCALE = 0.11, squish = 1, DESCSCALE = 1.1},'''
# match_indent = true

# 当前 Balasclo 版本
[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = "VERSION = VERSION..'-FULL'"
position = "after"
payload = "VERSION = VERSION..' (Balasclo v0.0.1)'"
overwrite = false
match_indent = true

# Steamodded 相关文本汉化
[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''label = {"MODS"},'''
position = "at"
payload = '''label = {"模组"},'''
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''label = "Mods",'''
position = "at"
payload = '''label = "模组",'''
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''label = " Steamodded Credits ",'''
position = "at"
payload = '''label = " Steamodded 鸣谢 ",'''
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''text = "List of Activated Mods",'''
position = "at"
payload = '''text = "已启用模组列表",'''
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''text = "List of Activated Mods",'''
position = "at"
payload = '''text = "已启用模组列表",'''
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''label = {" " .. modInfo.name .. " ", " By: " .. concatAuthors(modInfo.author) .. " "},'''
position = "at"
payload = '''label = {" " .. modInfo.name .. " ", "作者：" .. concatAuthors(modInfo.author) .. " "},'''
match_indent = true

# 减慢小丑牌名称渐入效果
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''pop_in_rate = 4,'''
position = "at"
payload = '''pop_in_rate = 1,'''
match_indent = true

# 使用轨道标签升级牌型的牌型名称本地化
[[patches]]
[patches.pattern]
target = "tag.lua"
pattern = '''handname= self.ability.orbital_hand,'''
position = "at"
payload = '''handname = localize(self.ability.orbital_hand, "poker_hands"),'''
match_indent = true

# “Not Allowed!”正确本地化
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''play_area_status_text("Not Allowed!")--localize('k_not_allowed_ex'), true)'''
position = "at"
payload = '''play_area_status_text(localize('k_not_allowed_ex'))'''
match_indent = true

# 页 x/x -> 第x/x页
[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''localize('k_page') .. ' ' .. tostring(i) .. '/' .. tostring(math.ceil(#G.P_CENTER_POOLS.Planet / 6)))'''
position = "at"
payload = ''''第' .. tostring(i) .. '/' .. tostring(math.ceil(#G.P_CENTER_POOLS.Planet / 6)) .. localize('k_page'))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''localize('k_page') .. ' ' .. tostring(i) .. '/' .. tostring(math.ceil(#G.P_CENTER_POOLS.Spectral / 9)))'''
position = "at"
payload = ''''第' .. tostring(i) .. '/' .. tostring(math.ceil(#G.P_CENTER_POOLS.Spectral / 9)) .. localize('k_page'))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''localize('k_page') .. ' ' .. tostring(i) .. '/' .. tostring(math.ceil(#G.P_CENTER_POOLS.Tarot / 11)))'''
position = "at"
payload = ''''第' .. tostring(i) .. '/' .. tostring(math.ceil(#G.P_CENTER_POOLS.Tarot / 11)) .. localize('k_page'))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''local currentPage = "Page " .. page .. "/" .. totalPages'''
position = "at"
payload = '''local currentPage = "第" .. page .. "/" .. totalPages .. "页"'''
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''table.insert(pageOptions, ("Page " .. i .. "/" .. totalPages))'''
position = "at"
payload = '''table.insert(pageOptions, ("第" .. i .. "/" .. totalPages .. "页"))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''table.insert(joker_options, localize('k_page')..' '..tostring(i)..'/'..tostring(math.ceil(#G.P_CENTER_POOLS.Joker/(5*#G.your_collection))))'''
position = "at"
payload = '''table.insert(joker_options, '第'..tostring(i)..'/'..tostring(math.ceil(#G.P_CENTER_POOLS.Joker/(5*#G.your_collection)))..localize('k_page'))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''table.insert(tarot_options, localize('k_page')..' '..tostring(i)..'/'..tostring(math.floor(#G.P_CENTER_POOLS.Tarot/11)))'''
position = "at"
payload = '''table.insert(tarot_options, '第'..tostring(i)..'/'..tostring(math.floor(#G.P_CENTER_POOLS.Tarot/11))..localize('k_page'))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''table.insert(booster_options, localize('k_page')..' '..tostring(i)..'/'..tostring(math.ceil(#G.P_CENTER_POOLS.Booster/8)))'''
position = "at"
payload = '''table.insert(booster_options, '第'..tostring(i)..'/'..tostring(math.ceil(#G.P_CENTER_POOLS.Booster/8))..localize('k_page'))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''table.insert(spectral_options, localize('k_page')..' '..tostring(i)..'/'..tostring(math.floor(#G.P_CENTER_POOLS.Spectral/9)))'''
position = "at"
payload = '''table.insert(spectral_options, '第'..tostring(i)..'/'..tostring(math.floor(#G.P_CENTER_POOLS.Spectral/9))..localize('k_page'))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''table.insert(voucher_options, localize('k_page')..' '..tostring(i)..'/'..tostring(math.ceil(#G.P_CENTER_POOLS.Voucher/(4*#G.your_collection))))'''
position = "at"
payload = '''table.insert(voucher_options, '第'..tostring(i)..'/'..tostring(math.ceil(#G.P_CENTER_POOLS.Voucher/(4*#G.your_collection)))..localize('k_page'))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''table.insert(challenge_options, localize('k_page')..' '..tostring(i)..'/'..tostring(math.ceil(#G.CHALLENGES/G.CHALLENGE_PAGE_SIZE)))'''
position = "at"
payload = '''table.insert(challenge_options, '第'..tostring(i)..'/'..tostring(math.ceil(#G.CHALLENGES/G.CHALLENGE_PAGE_SIZE))..localize('k_page'))'''
match_indent = true

# 随机商店副标题
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "function G.UIDEF.shop()"
position = "after"
payload = '''
function RollShopSub(seed)
    local vSub = localize('ph_improve_run')
    local shopSub = {
        vSub,
        "精打细算！",
        "消费无罪！",
        "Oh hi Johnny I didn't know it was you.",
        "客官里边请！",
        "命运之轮会欺骗你，但商店不会",
        "打造赛局最佳小丑阵容！",
        "更新日志：下架了金宝",
        "更新日志：上架了金宝",
        "留点资金吃利息？",
        "花 > 省",
        "接受信用卡！",
        "ALL IN!!!",
        "全场X折！",
        "金宝提醒您：早买早享受",
        "来点小丑牌？",
        "来点塔罗牌？",
        "来点星球牌？",
        "来点补充包？",
        "重掷即出好货！",
        "重掷即出负片！",
        "重掷即出镭射！",
        "重掷即出闪箔！",
        "重掷=浪费！",
        "你的贫穷让我沮丧！",
        "你的富裕让我痴狂！",
        "!!!$o$!!!",
        ".白.日.幻.梦.",
        "金宝严选好物！",
        "欢迎光临！",
        "童叟无欺！",
        "他们说你一毛不拔？",
        "他们说你挥金如土？",
        "看场电影吗？",
        "只手摘星！",
        "这里的塔罗牌算不了命",
        "祝你好运！",
        "没有好货别沮丧，下个路口见。",
        "听说有个Boss盲注会跳过商店？",
        "承认吧，你挥霍无度。",
        "如果你有鸡蛋，卖掉它。",
        "如果你有猪猪存钱罐，砸了它。",
        "Love from Balasclo.",
        "Balasclo is THE best.",
        "BALATRO CO., LTD.",
        "Love from Balachrom",
        "我无形，我歌唱。",
        "隐藏花色在哪里？",
        "每日上架最新款小丑！",
        "你也是小丑？",
        "我也是小丑？",
        "到底谁是小丑？",
        "哈哈，小丑买小丑",
        "人人都爱大金宝",
        "你也想拥有大金宝？",
        "Jimbo Limbo",
        "Jimbo bell, Jimbo bell",
        "Jimbo Jalapeno"
    }
    local sub = pseudorandom_element(shopSub, pseudoseed(seed))
    return sub
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.O, config={object = DynaText({string = {localize('ph_improve_run')}, colours = {lighten(G.C.GOLD, 0.3)},shadow = true, rotate = true, float = true, bump = true, scale = 0.5, spacing = 1, pop_in = 1.5, maxw = 4.3})}}'''
position = "at"
payload = '''{n=G.UIT.O, config={object = DynaText({string = {RollShopSub('ShopRandomSubGoBrr')}, colours = {lighten(G.C.GOLD, 0.3)},shadow = true, rotate = true, float = true, bump = true, scale = 0.5, spacing = 1, pop_in = 1.5, maxw = 4.3})}}'''
match_indent = true

# 移除英文/简中以外的语言选项
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
self.LANGUAGES = {
['en-us'] = {font = 1, label = "English", key = 'en-us', button = "Language Feedback", warning = {'This language is still in Beta. To help us','improve it, please click on the feedback button.', 'Click again to confirm'}},
['de'] = {font = 1, label = "Deutsch", key = 'de', beta = nil, button = "Feedback zur Übersetzung", warning = {'Diese Übersetzung ist noch im Beta-Stadium. Willst du uns helfen,','sie zu verbessern? Dann klicke bitte auf die Feedback-Taste.', "Zum Bestätigen erneut klicken"}},
['es_419'] = {font = 1, label = "Español (México)", key = 'es_419', beta = nil, button = "Sugerencias de idioma", warning = {'Este idioma todavía está en Beta. Pulsa el botón','de sugerencias para ayudarnos a mejorarlo.', "Haz clic de nuevo para confirmar"}},
['es_ES'] = {font = 1, label = "Español (España)", key = 'es_ES', beta = nil, button = "Sugerencias de idioma", warning = {'Este idioma todavía está en Beta. Pulsa el botón','de sugerencias para ayudarnos a mejorarlo.', "Haz clic de nuevo para confirmar"}},
['fr'] = {font = 1, label = "Français", key = 'fr', beta = nil, button = "Partager votre avis", warning = {'La traduction française est encore en version bêta. ','Veuillez cliquer sur le bouton pour nous donner votre avis.', "Cliquez à nouveau pour confirmer"}},
['id'] = {font = 1, label = "Bahasa Indonesia", key = 'id', beta = true, button = "Umpan Balik Bahasa", warning = {'Bahasa ini masih dalam tahap Beta. Untuk membantu','kami meningkatkannya, silakan klik tombol umpan balik.', "Klik lagi untuk mengonfirmasi"}},
['it'] = {font = 1, label = "Italiano", key = 'it', beta = nil, button = "Feedback traduzione", warning = {'Questa traduzione è ancora in Beta. Per','aiutarci a migliorarla, clicca il tasto feedback', "Fai clic di nuovo per confermare"}},
['ja'] = {font = 5, label = "日本語", key = 'ja', beta = nil, button = "提案する", warning = {'この翻訳は現在ベータ版です。提案があった場合、','ボタンをクリックしてください。', "もう一度クリックして確認"}},
['ko'] = {font = 4, label = "한국어", key = 'ko', beta = true, button = "번역 피드백", warning = {'이 언어는 아직 베타 단계에 있습니다. ','번역을 도와주시려면 피드백 버튼을 눌러주세요.', "다시 클릭해서 확인하세요"}},
['nl'] = {font = 1, label = "Nederlands", key = 'nl', beta = nil, button = "Taal suggesties", warning = {'Deze taal is nog in de Beta fase. Help ons het te ','verbeteren door op de suggestie knop te klikken.', "Klik opnieuw om te bevestigen"}},
['pl'] = {font = 1, label = "Polski", key = 'pl', beta = nil, button = "Wyślij uwagi do tłumaczenia", warning = {'Polska wersja językowa jest w fazie Beta. By pomóc nam poprawić',' jakość tłumaczenia, kliknij przycisk i podziel się swoją opinią i uwagami.', "Kliknij ponownie, aby potwierdzić"}},
['pt_BR'] = {font = 1, label = "Português", key = 'pt_BR', beta = nil, button = "Feedback de Tradução", warning = {'Esta tradução ainda está em Beta. Se quiser nos ajudar','a melhorá-la, clique no botão de feedback por favor', "Clique novamente para confirmar"}},
['ru'] = {font = 6, label = "Русский", key = 'ru', beta = true, button = "Отзыв о языке", warning = {'Этот язык все еще находится в Бета-версии. Чтобы помочь','нам его улучшить, пожалуйста, нажмите на кнопку обратной связи.', "Щелкните снова, чтобы подтвердить"}},
['zh_CN'] = {font = 2, label = "简体中文", key = 'zh_CN', beta = nil, button = "意见反馈", warning = {'这个语言目前尚为Beta版本。 请帮助我们改善翻译品质，','点击”意见反馈” 来提供你的意见。', "再次点击确认"}},
['zh_TW'] = {font = 3, label = "繁體中文", key = 'zh_TW', beta = nil, button = "意見回饋", warning = {'這個語言目前尚為Beta版本。請幫助我們改善翻譯品質，','點擊”意見回饋” 來提供你的意見。', "再按一下即可確認"}},
['all1'] = {font = 8, label = "English", key = 'all', omit = true},
['all2'] = {font = 9, label = "English", key = 'all', omit = true},
        }
'''
position = "at"
payload = '''
self.LANGUAGES = {
['zh_CN'] = {font = 2, label = "简体中文", key = 'zh_CN', beta = nil, button = "意见反馈", warning = {"Balasclo"}},
['en-us'] = {font = 1, label = "English", key = 'en-us', beta = true, button = "Language Feedback", warning = {'Balasclo is currently live in your game.','Switching language may result in certain texts failing to be displayed.','Only suggested for testing. Click again to proceed.'}},
['all1'] = {font = 8, label = "English", key = 'all', omit = true},
['all2'] = {font = 9, label = "English", key = 'all', omit = true},
}
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''definition = create_UIBox_card_alert({no_bg = true, text = 'BETA', scale = 0.35}),'''
position = "at"
payload = '''definition = create_UIBox_card_alert({no_bg = true, text = '', scale = 0.35}),'''
match_indent = true

# 强制简中
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
G.SETTINGS.language = 'en-us'
end
-------------------------------------------------------
--IF LANGUAGE NEEDS TO BE SET ON EVERY REBOOT, SET HERE

-------------------------------------------------------
'''
position = "at"
payload = '''
G.SETTINGS.language = 'zh_CN'
end
-------------------------------------------------------
--IF LANGUAGE NEEDS TO BE SET ON EVERY REBOOT, SET HERE
G.SETTINGS.language = 'zh_CN'
-------------------------------------------------------
'''
match_indent = true

# 跳过教程（ TUTORIAL ）
[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = '''
self.F_SKIP_TUTORIAL = false            --Completely skip the tutorial on fresh save
'''
position = "at"
payload = '''
self.F_SKIP_TUTORIAL = true            --Completely skip the tutorial on fresh save
'''
match_indent = true
