[manifest]
version = "0.1"
dump_lua = false
priority = 0

# [[patches]]
# [patches.pattern]
# target = "game.lua"
# pattern = '''{file = "resources/fonts/NotoSansSC-Bold.ttf", render_scale = self.TILESIZE*7, TEXT_HEIGHT_SCALE = 0.7, TEXT_OFFSET = {x=0,y=-35}, FONTSCALE = 0.12, squish = 0.9, DESCSCALE = 1.1},'''
# position = "at"
# payload = '''{file = "resources/fonts/NotoSansSC-Bold.ttf", render_scale = self.TILESIZE*7, TEXT_HEIGHT_SCALE = 0.9, TEXT_OFFSET = {x=0,y=-3}, FONTSCALE = 0.11, squish = 1, DESCSCALE = 1.1},'''
# match_indent = true

# 当前 Balasclo 版本
[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = "VERSION = VERSION..'-FULL'"
position = "after"
payload = "VERSION = VERSION..' (Balasclo v0.0.1)'"
overwrite = false
match_indent = true

# Steamodded 相关文本汉化
[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''label = {"MODS"},'''
position = "at"
payload = '''label = {"模组"},'''
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''label = "Mods",'''
position = "at"
payload = '''label = "模组",'''
match_indent = true

# 使用轨道标签升级牌型的牌型名称本地化
[[patches]]
[patches.pattern]
target = "tag.lua"
pattern = '''handname= self.ability.orbital_hand,'''
position = "at"
payload = '''handname = localize(self.ability.orbital_hand, "poker_hands"),'''
match_indent = true

# “Not Allowed!”正确本地化
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''play_area_status_text("Not Allowed!")--localize('k_not_allowed_ex'), true)'''
position = "at"
payload = '''play_area_status_text(localize('k_not_allowed_ex'))'''
match_indent = true
