name: Package Repository

on:
  push:
    branches:
      - overlord
    paths:
      - 'Mods/**'
      - 'resources/**'
      - 'localization/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.5
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Remove unwanted files and directories
      run: |
        rm -rf .gitignore .gitmodules .github
        rm -rf Mods/Betmma-mods/Betmma_Voucher_Pack
        rm -rf Mods/Betmma-mods/5_legendary_challenges
        rm -rf Mods/Codex-Arcanum/art Mods/Codex-Arcanum/doc
        find . -type d -name '.git' -exec rm -rf {} +
        find . -type f -name '.git' -exec rm -rf {} +
        find . -type f -iname 'README.md' -exec rm -f {} +
        find . -type f -iname 'CHANGELOG.md' -exec rm -f {} +
        find . -type f -iname 'LICENSE' -exec rm -f {} +

    - name: CA arrange
      run: |
        mv Mods/Codex-Arcanum/mod Mods/ca-temp
        rm -rf Mods/Codex-Arcanum
        mv Mods/ca-temp Mods/Codex-Arcanum

    - name: DX-Tarots arrange
      run: |
        mv Balachrom/Tarots_dx1x.png Mods/DX-Tarots/assets/1x/
        mv Balachrom/Tarots_dx2x.png Mods/DX-Tarots/assets/2x/
        mv Mods/DX-Tarots/assets/1x/Tarots_dx1x.png Mods/DX-Tarots/assets/1x/Tarots_dx.png
        mv Mods/DX-Tarots/assets/2x/Tarots_dx2x.png Mods/DX-Tarots/assets/2x/Tarots_dx.png

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: pack_snapshot.zip
        path: ./
