name: Package Repository

on:
  push:
    branches:
      - overlord
    paths:
      - 'Mods/**'
      - 'resources/**'
      - 'localization/**'
      - '.github/workflows/package.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.5
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Mod files arrange
      run: |
        echo "_______Myst's Mods"
        PATH="Mods/MystMods"
        mv $PATH/Steamodded/MystBlinds $PATH/MystBlinds
        mv $PATH/Steamodded/MystJokers $PATH/MystJokers
        rm -rf $PATH/{Steamodded,Balamod,Infodumps}
        
        echo "_______Codex Arcanum"
        mv Mods/Codex-Arcanum/mod Mods/ca-temp
        rm -rf Mods/Codex-Arcanum
        mv Mods/{ca-temp,Codex-Arcanum}

        echo "_______BossJokers"
        mv Mods/BossJokers/BossJokers/* Mods/BossJokers/
        rm -rf Mods/BossJokers/BossJokers

        echo "_______Steamodded"
        mv Mods/Steamodded/example_mods/Mods/MoreSpeeds.lua Mods/MoreSpeeds.lua
        
        echo "_______DX Tarots"
        PATH="Mods/DX-Tarots"
        mv Balachrom/Tarots_dx1x.png $PATH/assets/1x/
        mv Balachrom/Tarots_dx2x.png $PATH/assets/2x/
        mv $PATH/assets/1x/Tarots_dx1x.png $PATH/assets/1x/Tarots_dx.png
        mv $PATH/assets/2x/Tarots_dx2x.png $PATH/assets/2x/Tarots_dx.png

    - name: Remove unwanted files and directories
      run: |
        rm -rf .gitignore .gitmodules .github
        rm -rf Mods/Betmma-mods/Betmma_Voucher_Pack
        rm -rf Mods/Betmma-mods/5_legendary_challenges
        rm -rf Mods/Codex-Arcanum/art Mods/Codex-Arcanum/doc
        rm -rf Mods/Steamodded/7-zip Mods/Steamodded/example_mods Mods/Steamodded/requirements.txt
        find ./Mods -maxdepth 2 -type f -name 'icon.png' -exec rm -f {} +
        find ./Mods -maxdepth 2 -type f -name 'index.html' -exec rm -f {} +
        find ./Mods -maxdepth 2 -type f -name 'm6x11plus.ttf' -exec rm -f {} +
        find . -type d -name '.git' -exec rm -rf {} +
        find . -type d -name 'site' -exec rm -rf {} +
        find . -type d -name '.github' -exec rm -rf {} +
        find . -type d -name '.vscode' -exec rm -rf {} +
        find . -type d -name 'gitresources' -exec rm -rf {} +
        find . -type f -name '*.py' -exec rm -f {} +
        find . -type f -name '*.sh' -exec rm -f {} +
        find . -type f -name '*.bat' -exec rm -f {} +
        find . -type f -name '*.ps1' -exec rm -f {} +
        find . -type f -name '.git' -exec rm -rf {} +
        find . -type f -iname 'LICENSE' -exec rm -f {} +
        find . -type f -iname 'style.css' -exec rm -f {} +
        find . -type f -iname 'README.md' -exec rm -f {} +
        find . -type f -iname 'README.asc' -exec rm -f {} +
        find . -type f -name '.gitignore' -exec rm -rf {} +
        find . -type f -iname 'changelog.md' -exec rm -f {} +
        find . -type f -iname 'addjokers.js' -exec rm -f {} +
        find . -type f -iname 'CHANGELOG.md' -exec rm -f {} +
        find . -type f -iname 'manifest.json' -exec rm -f {} +
        find . -type f -name '.gitattributes' -exec rm -rf {} +
        find . -type f -iname 'generate_sprite.fish' -exec rm -f {} +

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: pack_snapshot.zip
        path: ./
