name: Package Repository

on:
  push:
    branches:
      - overlord
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Remove unwanted files and directories
      run: |
        rm -rf .gitignore .gitmodules .github
        rm -rf Mods/Betmma-mods/Betmma_Voucher_Pack
        rm -rf Mods/Betmma-mods/5_legendary_challenges
        rm -rf Mods/Codex-Arcanum/art Mods/Codex-Arcanum/doc
        find . -type d -name '.git' -exec rm -rf {} +
        find . -type f -name '.git' -exec rm -rf {} +
        find . -type f -iname 'README.md' -exec rm -f {} +
        find . -type f -iname 'LICENSE' -exec rm -f {} +

    - name: Move and rename directory
      run: |
        mv Mods/Codex-Arcanum/mod Mods/ca-temp
        rm -rf Mods/Codex-Arcanum
        mv Mods/ca-temp Mods/Codex-Arcanum

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: pack_snapshot.zip
        path: ./
